apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fat1d03qh-nodejs
  janus-idp.io/tekton: fat1d03qh-nodejs
  backstage.io/kubernetes-id: fat1d03qh-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fat1d03qh-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
